### ISSUE TITLE
Plugin is not working anymore :(

### ISSUE THREAD

**Issue by Dagrond** [mmopluginteam/mmoitems-mana#4]
`[17:39:01] [Server thread/INFO]: [MMOMana] Enabling MMOMana v1.3.4
[17:39:01] [Server thread/ERROR]: Error occurred while enabling MMOMana v1.3.4 (Is it up to date?)
java.lang.ClassCastException: class net.Indyuce.mmoitems.comp.rpg.DefaultHook cannot be cast to class org.bukkit.plugin.Plugin (net.Indyuce.mmoitems.comp.rpg.DefaultHook is in unnamed module of loader 'MMOItems-6.10-20240221.183207-3.jar' @114d9864; org.bukkit.plugin.Plugin is in unnamed module of loader java.net.URLClassLoader @1ed6993a)
	at net.Indyuce.mmoitems.MMOItems.setRPG(MMOItems.java:371) ~[MMOItems-6.10-20240221.183207-3.jar:?]
	at eu.asangarin.mana.MMOMana.onEnable(MMOMana.java:49) ~[MMOMana-1.3.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2148]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2148]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2148]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2148]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2148]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2148]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2148]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2148]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2148]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[17:39:01] [Server thread/INFO]: [MMOMana] Disabling MMOMana v1.3.4`

MMOItems 6.10-SNAPSHOT
MythicLib 1.6.2-SNAPSHOT
Purpur 1.20.4

**Comment by Dagrond** [comment]
After some testing, this issue is clearly because bugged MMOItems source code, not because of this plugin. Yet, I will not delete this to warn other that in current MMOItems state, this plugin is not usable.
